# Generated by Django 5.0 on 2024-01-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_formulario', '0004_remove_editarcampos_espectativasentrevistado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editarcampos',
            name='lugarNacimientoEstudiante',
        ),
    ]
