# Generated by Django 5.0 on 2024-01-08 20:45

import editor_formulario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_formulario', '0005_remove_editarcampos_lugarnacimientoestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editarcampos',
            name='ocupacion',
            field=models.JSONField(default=editor_formulario.models.DefaultOcupacion),
        ),
    ]
