# Generated by Django 5.0 on 2024-01-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=500, verbose_name='Nombre')),
                ('archivo', models.FileField(upload_to='piars/')),
            ],
            options={
                'verbose_name': 'Piar',
                'verbose_name_plural': 'Piars',
            },
        ),
    ]
