# Generated by Django 5.0 on 2024-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piar',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
