# Generated by Django 5.0 on 2023-12-15 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atencion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='form_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
