# Generated by Django 5.0 on 2023-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atencion', '0002_registro_created_registro_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
