# Generated by Django 5.0 on 2023-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atencion', '0003_registro_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
