# Generated by Django 5.0 on 2023-12-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atencion', '0004_registro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='consecutivo',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
