# Generated by Django 5.0 on 2023-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atencion', '0005_alter_registro_consecutivo_alter_registro_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.RemoveField(
            model_name='registro',
            name='acuerdosPrevios',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='compromisoEstudiantes',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='compromisoPadres',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='piar',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='remision',
        ),
        migrations.AddField(
            model_name='registro',
            name='acuerdosPrevios',
            field=models.ManyToManyField(blank=True, related_name='acuerdosPrevios', to='registro_de_atencion.archivo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='compromisoEstudiantes',
            field=models.ManyToManyField(blank=True, related_name='compromisoEstudiantes', to='registro_de_atencion.archivo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='compromisoPadres',
            field=models.ManyToManyField(blank=True, related_name='compromisoPadres', to='registro_de_atencion.archivo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='piar',
            field=models.ManyToManyField(blank=True, related_name='piar', to='registro_de_atencion.archivo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='remision',
            field=models.ManyToManyField(blank=True, related_name='remision', to='registro_de_atencion.archivo'),
        ),
    ]
