# Generated by Django 5.0 on 2023-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atencion', '0007_alter_registro_acuerdosprevios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='acuerdosPrevios',
            field=models.ManyToManyField(blank=True, related_name='acuerdosPrevios', to='registro_de_atencion.archivo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='compromisoEstudiantes',
            field=models.ManyToManyField(blank=True, related_name='compromisoEstudiantes', to='registro_de_atencion.archivo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='compromisoPadres',
            field=models.ManyToManyField(blank=True, related_name='compromisoPadres', to='registro_de_atencion.archivo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='piar',
            field=models.ManyToManyField(blank=True, related_name='piar', to='registro_de_atencion.archivo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='remision',
            field=models.ManyToManyField(blank=True, related_name='remision', to='registro_de_atencion.archivo'),
        ),
    ]
