# Generated by Django 5.0 on 2023-12-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_atencion', '0008_alter_registro_acuerdosprevios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='acudiente',
        ),
        migrations.AddField(
            model_name='registro',
            name='edadEstudiante',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='hogarYBienestar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='nombreRemitidoPor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='numeroTelefonoEstudiante',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='personaDeConfianza',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
